# wttr package

name: wttr
parent: default

matches:
  - trigger: ":wttrin"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: Invoke-WebRequest https://it.wttr.in/?format="%l:+%c+%t+%w\n" | Select-Object -Expand Content

  - trigger: ":moonphase"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: Invoke-WebRequest https://wttr.in?format="%m\n" | Select-Object -Expand Content

  - trigger: ":wttrat"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: Invoke-WebRequest https://it.wttr.in/{{location}}?format="%l:+%c+%t+%w\n" | Select-Object -Expand Content
